### ISSUE TITLE
[Front End] Create a listing page with all entries from DSM-V

### ISSUE THREAD

**Issue by ethanbwaite** [allenzhai/308-Project#52]

**Comment by Hobbes1118** [comment]
#24

**Comment by Andrii-I** [comment]
As discussed, a page is a list of groups of conditions (empty hyperlinks at the moment, to be populated with conditions)

**Comment by Andrii-I** [comment]
Submitted the pull request. The list is hardcoded for now but for future, we should create a pipeline that would generate the page from the list of groups of conditions from database dynamically

**Comment by Andrii-I** [comment]
Done
