### ISSUE TITLE
[Front End] Create a landing page

### ISSUE THREAD

**Issue by ethanbwaite** [allenzhai/308-Project#54]

**Comment by ethanbwaite** [comment]
#21

**Comment by zzheng07** [comment]
Group Estimate = 3 hours

**Comment by zzheng07** [comment]
Subtask
1. Document the framework so others can integrate their work into it

**Comment by zzheng07** [comment]
Hi, @ethanbwaite could you please remove the `node_modules` folder in your next commit? The files in that folder are constantly updated and can easily clutter our repo. As long as we have `package.json` file, others can always get the project running in no time. Thanks.

**Comment by ethanbwaite** [comment]
Actual: 3 hours
